export enum TwitterClientState {
  TWITTER_STARTUP = 'TWITTER_STARTUP',
  TWITTER_LOGIN_COOKIE_INIT = 'TWITTER_LOGIN_COOKIE_INIT',
  TWITTER_LOGIN = 'TWITTER_LOGIN',
  TWITTER_PROFILE_INIT = 'TWITTER_PROFILE_INIT',
  TWITTER_POPULATE_TIMELINE = 'TWITTER_POPULATE_TIMELINE',
}

export enum TwitterClientStatus {
  RUNNING = 'RUNNING',
  STOPPING = 'STOPPING',
  STOPPED = 'STOPPED',
  STOP_FAILED = 'STOP_FAILED',
  ERROR = 'ERROR',
}
